# Example configuration for synthetic questions generation
# This is equivalent to the example.sh script but in YAML format

# Dataset configuration
dataset: "mkurman/hindawi-journals-2007-2023"

# Provider configuration
provider: "openrouter"
model: "qwen/qwen3-235b-a22b-2507"

# Output configuration
output_dir: "./data/questions_openrouter"

# Dataset processing configuration
start_index: 0
end_index: 10
text_column: "text"

# Question generation configuration
num_questions: 5

# Execution configuration
verbose: true

# Optional configurations (with default values shown)
# max_tokens: 4096
# num_workers: 1
# shuffle: false
# sleep_between_requests: 0.0
# sleep_between_items: 0.0
# rate_limit_wait: 15.0
# rate_limit_retries: 1

# Style configuration (uncomment to use)
# style: "formal and academic"
# styles_file: "./styles_sample.txt"
# no_style: false

# Answer generation (uncomment to enable)
# with_answer: true
# answer_provider: "openrouter"  # Optional, defaults to main provider
# answer_model: "qwen/qwen3-235b-a22b-2507"  # Optional, defaults to main model
# answer_single_request: false

# Multiple-choice questions (uncomment to enable)
# with_options: true

# Custom provider URL (required when provider is "other")
# provider_url: "https://api.example.com/v1"

# Environment variables needed:
# OPENROUTER_API_KEY=your_api_key_here
